[tool.poetry]
name = "led-effect-tests"
version = "0.1.0"
authors = ["Julian Schill <j.schill@web.de>"]
description = ""
package-mode = false

[tool.poetry.dependencies]
python = "<3.12,>=3.8"
klippermock = {path = "../klippermock", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.1"
pytest-golden = "^0.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
