[tool.poetry]
name = "preview-generator"
version = "0.1.0"
authors = ["reemo3dp"]
description = ""
package-mode = false

[tool.poetry.dependencies]
python = "<3.12,>=3.8"
klippermock = {path = "../klippermock", develop = true}
pillow = "^10.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
