name: Update Previews
on:
  workflow_dispatch:
  push:
    paths:
      - '*.md'
      - 'docs/*.md'
      - 'docs/**/*.md'
    branches:
      - main

jobs:
  update_previews:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      working-directory: ./packages/preview_generator
      run: poetry install
    - name: Delete all previews
      working-directory: .
      run: |
        set -x
        git rm -f preview_*.gif || true
        git rm -f docs/preview_*.gif || true
        git rm -f docs/**/preview_*.gif || true
    - name: Update all previews
      working-directory: ./packages/preview_generator
      run: |
        set -x
        for i in $(ls $GITHUB_WORKSPACE/*.md $GITHUB_WORKSPACE/docs/**/*.md $GITHUB_WORKSPACE/docs/*.md); do
          poetry run python markdown_generator.py --directory img "$i"
        done
    - name: Commit changes
      working-directory: .
      run: |
        set -euxo pipefail
        git config --global user.name "GitHub Actions"
        git config --global user.email "githubactions@github.com"
        git add preview_*.gif || true
        git add *.md || true
        git add docs/**/*.md || true
        git add docs/**/preview_*.gif || true
        git add docs/*.md || true
        git add docs/preview_*.gif || true
        git diff --staged --quiet && exit 0 || true

        git commit -m "chore(docs): Update previews"
        git push origin HEAD:${GITHUB_REF}
